metadata:
  namespace: # setar o namespace do GCP
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: commons-key
      containers:
        - volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: DB_URL
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: db.url
            - name: DB_USERNAME
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: db.username
            - name: DB_PASSWORD
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: db.password
            - name: SUBSCRIPTION_NAME
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: subscription.name
            - name: TOPIC_OUT_NAME
              valueFrom:
               configMapKeyRef:
                  name: ${project.artifactId}
                  key: topic.out.name
          imagePullPolicy: Always
