spring:
  datasource:
    url: jdbc:mysql://35.198.30.27:3306/boletos
    username: boletos
    password: boletos
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
subscription:
  name: boletos-in
topic:
  out:
    name: boletos-out